- name : This is the loadbalancer yaml
  hosts: localhost
  tasks:
    - name: create loadbalancer_image
      docker_image:
        name: loadbalancer_image
        build: 
            path: .
        source: build
    - name: create loadbalancer_container
      docker_container:
        name: docker_container
        image: loadbalancer_image